- hosts: google cloud engine
  remote_user: kiki44552002
  sudo: True

  tasks:
    - name: Install nginx web server
      apt:  pkg=nginx update_cache=yes

    - name: Copy nginx-default
      copy: src=./nginx-default dest=/etc/nginx/sites-available/default
      notify: Restart nginx

    - name: Copy nginx.conf
      copy: src=./nginx.conf dest=/etc/nginx/nginx.conf
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service: name=nginx state=restarted
